module(...)

-- This file is for use with Love2d and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getFrames()
	local frames = {
		
			{
				name = "door_closed",
				rect = { x = 2, y = 20, width = 16, height = 16 }, 
			},
		
			{
				name = "door_open",
				rect = { x = 2, y = 2, width = 16, height = 16 }, 
			},
		
			{
				name = "wall_1",
				rect = { x = 20, y = 2, width = 16, height = 16 }, 
			},
		
	}

	return frames
end