module(...)

-- This file is for use with Love2d and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getFrames()
	local frames = {
		
			{
				name = "background_1",
				rect = { x = 2, y = 72, width = 16, height = 16 }, 
			},
		
			{
				name = "chest.png",
				rect = { x = 34, y = 63, width = 16, height = 16 }, 
			},
		
			{
				name = "door_closed",
				rect = { x = 2, y = 90, width = 16, height = 16 }, 
			},
		
			{
				name = "door_open",
				rect = { x = 2, y = 54, width = 16, height = 16 }, 
			},
		
			{
				name = "flaming_skull",
				rect = { x = 34, y = 2, width = 16, height = 21 }, 
			},
		
			{
				name = "goblin",
				rect = { x = 34, y = 25, width = 16, height = 18 }, 
			},
		
			{
				name = "golem",
				rect = { x = 2, y = 2, width = 30, height = 32 }, 
			},
		
			{
				name = "mushroom",
				rect = { x = 2, y = 36, width = 16, height = 16 }, 
			},
		
			{
				name = "player",
				rect = { x = 20, y = 78, width = 10, height = 16 }, 
			},
		
			{
				name = "slime_blue_1",
				rect = { x = 48, y = 81, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_blue_2",
				rect = { x = 52, y = 16, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_blue_3",
				rect = { x = 20, y = 64, width = 12, height = 12 }, 
			},
		
			{
				name = "slime_green_1",
				rect = { x = 52, y = 2, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_green_2",
				rect = { x = 52, y = 28, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_green_3",
				rect = { x = 20, y = 50, width = 12, height = 12 }, 
			},
		
			{
				name = "slime_red_1",
				rect = { x = 32, y = 81, width = 14, height = 12 }, 
			},
		
			{
				name = "slime_red_2",
				rect = { x = 68, y = 2, width = 16, height = 10 }, 
			},
		
			{
				name = "slime_red_3",
				rect = { x = 20, y = 36, width = 12, height = 12 }, 
			},
		
			{
				name = "wall_1",
				rect = { x = 34, y = 45, width = 16, height = 16 }, 
			},
		
	}

	return frames
end